### ISSUE TITLE
waitForConnectedPeer() does not wait

### ISSUE THREAD

**Issue by dao** [status-im/js-waku#420]
This is a **bug report**

## Problem

`await waku.waitForConnectedPeer()` does not actually wait for connected peers

In the following code snippet and log, you can see that `getPeers` returns an empty set after calling `await waku.waitForConnectedPeer()`. After manually waiting 2 seconds, the second call to `getPeers` is not empty. 
```
  waku = await Waku.create({ bootstrap: true });
  log('await waku.waitForConnectedPeer()');
  await waku.waitForConnectedPeer();
  log('waku.relay.getPeers():', waku.relay.getPeers());
  log('sleep 2s');
  await sleep(2000);
  log('waku.relay.getPeers():', waku.relay.getPeers());
```
log:
```
await waku.waitForConnectedPeer()
waku.relay.getPeers(): Set(0) {} <---- unexpected
sleep 2s
waku.relay.getPeers(): Set(1) { '16Uiu2HAmL5okWopX7NqZWBUKVqW8iUxCEmd5GMHLVPwCgzYzQv3e' } <---- expected
```

## Proposed Solutions

`await waku.waitForConnectedPeer()` should wait until a peer is actually connected 

## Notes

- js-waku version: 0.14.2 AND 0.15.0
- node version: 16.6.2
- ubuntu 20.04 under wsl2

**Comment by D4nte** [comment]
Investigation done.

The behavior is actually _expected_. `Waku.waitForConnectedPeer()` returns the peers that are _connected_ and _identified_ by the libp2p node.

`WakuRelay.getPeers` returns the peers that are part of the gossipsub sub mesh. ie, peers to whom relay messages are sent and peers that would forward relay messages.

Learn more about _mesh_ in the gossipsub specs: https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.0.md#gossipsub-the-gossiping-mesh-router

If `getPeers` does not return peers just after `waitForConnectedPeers` it is because some processing needs to be done and control messages need to be exchanged for peers to be in each other's mesh.

Moving forward I can see several solutions that can be implemented separately or together:
1. Rename `getPeers` to `getPeersInMesh` to make it clearer that the peers returned are not just any connected waku relay peer.
2. Provide a `waitForPeersInMesh` method on `WakuRelay` that would simply wait for peer to be part of the gossipsub mesh

@dao, let me know if implementing the 2 solutions would help or if you would like another API to fit your needs.

**Comment by dao** [comment]
from the examples and docs I've seen, awaiting `waitForConnectedPeers` signals that everything is ready to go - ie, that messages can be relayed . If "everything is ready to go" means that peers are in mesh, then I would lean towards the contents of `waitForConnectedPeers` being replaced rather than adding a new function `waitForPeersInMesh` since the existing examples devs find (eg waku uber) are unlikely to be updated  from `waitForConnectedPeers` to `waitForPeersInMesh` when the latter is actually intended.

**Comment by D4nte** [comment]
Sounds good. Will action.

**Comment by D4nte** [comment]
You can use this workaround in the meantime, after or instead of `waitForConnectedPeers`.

```ts
      await new Promise((resolve) =>
        waku.libp2p.pubsub.once('pubsub:subscription-change', () =>
          resolve(null)
        )
```

**Comment by D4nte** [comment]
After further investigation and the implementation of `waitForRemotePeer`, I'd like to clarify that there is no way to _guarantee_ that a relay node is ready on both sides.
Indeed, for Alice to start sending messages to Bob via relay, the following needs to happen:

1. Alice connects to Bob
2. Alice & Bob exchange `identify` messages, both agree to open a stream with `relay` protocol.
3. Alice sends a `subscribe` to Bob for Waku Relay default pubsub topic
4. Bob processes the `subscribe` by adding Alice to the peers for the given pubsub topic and sends a `subscribe` too.
5. Alice needs to maintain her gossipsub mesh (heartbeat), if there are not enough peers (less than 6) in the mesh for the given pubsub topic then she'll add a peer from the topic to it (Bob), send a CTRL GRAFT message to Bob. Now Alice will forward messages to Bob for the given topic.
6. Bob does the same.

For Alice's point of view, it is possible to know if steps 1 to 5 have happened and that is what `waitForRemotePeer` does.

However, Alice cannot know (as far as I understand) whether step 6 happened. So while Alice may start sending relay messages from 5, Bob may not send relay messages to Alice just yet.

So in a test environment, I see no choice but waiting a bit: https://github.com/status-im/js-waku/blob/b257885204ecfc5c8357824ed76fa6d0728740a1/src/lib/waku_message/index.node.spec.ts#L49

In a production environment, other steps should happen (such as retrieving messages using Waku Store) before an app is "ready". so the race condition is not as likely.

Note that work is in progress to make the `WakuRelay.send` method provide more feedback and actually return the recipients to whom a message was sent: https://github.com/libp2p/js-libp2p-interfaces/pull/119
