### ISSUE TITLE
Why can't I find historical information

### ISSUE THREAD

**Issue by xyy0725** [status-im/js-waku#597]
Js-waku  'queryHistory' could not find the message sent before

"js-waku": "^0.18.0",

const waku = await Waku.create({bootstrap: {default: true}});

waku.waitForRemotePeer().then(()=>{
 ...................
})

//  waku.store.queryHistory(ChatContentTopic, {
          pageSize: 1,
          pageDirection: 'forward',
          timeFilter: {
            startTime,
            endTime
          },
          callback
        })  
//      No messages present in HistoryRPC response  ？？？？？     There should be information

//      waku.relay.addObserver(callback, ChatContentTopic)         This function and the send function are normal

//      And like it        https://js-waku.wakuconnect.dev/examples/web-chat/           
//     The message sent, refreshed, disappeared

**Comment by D4nte** [comment]
Maybe there are no message in the history at the given time, where there messages when you loaded https://js-waku.wakuconnect.dev/examples/web-chat? 

We are also aware of issues with store: https://github.com/status-im/nim-waku/issues/841

It is fixed in nim-waku 0.8 but I don't believe it is deployed yet.

What content topic did you use?

Finally, please use markdown to write issue so it can be easier to read:

https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github

**Comment by D4nte** [comment]
@xyy0725 I guess it was working before? This might related to the new nim-waku release: https://github.com/status-im/nim-waku/issues/882

**Comment by D4nte** [comment]
I think we found the culprit:
- nim-waku: https://github.com/status-im/nim-waku/pull/878 this is now deployed on the test fleet. a new release needs to happen and be deployed on prod fleet
- js-waku: #606 

Will release today but you would need to use the test fleet.
