### ISSUE TITLE
Convert library to ESM Only

### ISSUE THREAD

**Issue by D4nte** [status-im/js-waku#755]
libp2p dependencies are being converted to ESM: https://github.com/libp2p/js-libp2p/blob/master/doc/migrations/v0.36-v.037.md#esm

The recommended way forward is to also migrate to ESM.

**Comment by D4nte** [comment]
Previous work: https://github.com/status-im/js-waku/pull/433

**Comment by prichodko** [comment]
I don't fully understand this issue. Waku already has an ESM build.

I will open an issue on their repo, but this is not the correct way when you publish your library both for Node.js and browsers *yet*.

If `libp2p` targeted only `Node.js`, then you can specify the `engines` field and require your users to use the Node.js version where ES Modules are supported. However, since they also target browsers I would strongly recommend avoiding such a breaking change because the ecosystem is still in the process of adopting this.

An example would be the [resolve](https://www.npmjs.com/package/resolve) package with 50 million weekly downloads upon many other tools depend – https://github.com/browserify/resolve/issues/222. Parcel also does not support this yet (https://github.com/parcel-bundler/parcel/issues/4155).

**Comment by prichodko** [comment]
After giving it a second thought, I realized I am mixing two different things here:
1. Packages being ESM only
2. Backwards compatibility

I think it is _probably_ okay to move to ESM only package and dropping support for Node.js versions not supporting ESM, which means <12.0.0. However, I think it's too early to rely solely on `exports` field in `package.json` if you are targeting different environments than `Node.js`. I would recommend keeping using the "module" field for compatibility with older bundlers and an Export Map for compatibility with Node.js v12+ and future bundlers.

**Comment by D4nte** [comment]
If I understand correctly, you recommend keeping the `module` field in the `package.json` to help with backward compatiblity?
